### PR TITLE
Added options to filter out different Rank Spells.

### PR DESCRIPTION
**Pull request by losjoe**
I added four checkboxes that would let the user filter out different ranked spells.

### CODE REVIEW

**Comment by rumstil** [comment]
Thanks for your contribution. I'm am reviewing this and may need to make a few tweaks.

**Comment by losjoe** [comment]
No problem.  I was trying to make some spell lists that were easier to look at without the extra ranks and the stand alone version was close to doing what I wanted it to do.  I figured that after I got the filter working for the most part that I might as well share it back.   I couldn't get the forward references for certain things to not show up with the removal of the Rk 0 stuff, but I also didn't fully understand how those references came around.  If there's anything else I can do, let me know.

**Comment by losjoe** [comment]
Going to try to merge your newest commit with my changes.

**Comment by rumstil** [comment]
I've merged this in - but made a bit of a mess of it because still trying to figure out merges.

I changed the checkboxes to a dropdown to reduce screen clutter.

**Pull request closed without merging**
